### ISSUE TITLE
I can not get Live Image Stream with Recognition

### ISSUE THREAD

**Issue by xxtkidxx** [dan246/VisionFlow#2]
Hello @dan246 
I am very interested in your project.
I installed according to your instructions and was able to livestream the camera from http://localhost:15440/get_stream/1
However I can't see the processed image from the address http://localhost:15440/recognized_stream/1
I don't know where to start to check for errors and handle them
Please see and help me. I have included some installation photos
![image](https://github.com/user-attachments/assets/c99f5a95-aa44-4037-bd7e-2fdc774dcd10)
![image](https://github.com/user-attachments/assets/52d8e2b1-0bf0-4022-a893-3d1ff6152253)
![image](https://github.com/user-attachments/assets/88616966-12a9-4cb6-aec9-57bdfcc4bbe3)
![image](https://github.com/user-attachments/assets/9c6cf854-b0a0-4016-9d9d-7967dd0b45fb)
![image](https://github.com/user-attachments/assets/6c23a39e-1c29-4b65-acac-b56c9c8aa1e1)
![image](https://github.com/user-attachments/assets/95eabfe5-7c6d-4de6-81d7-afc95bf371db)

**Comment by dan246** [comment]
Hi @xxtkidxx , sorry for the late reply. This error message seems to indicate that the model has not been set. The recognized_stream/<ID> API requires streaming after model recognition, so please make the following PATCH request using curl:
`curl -X PATCH http://<your-server>/cameras/<camera_id> \
-H "Authorization: Bearer <your_token>" \
-H "Content-Type: application/json" \
-d '{
    "name": "new_name",
    "stream_url": "new_stream_url",
    "recognition": "model_name"
}'
`
Or, you can modify the model through the camera management section on the admin page. 

ps. The model names can be configured in object_recognition/model_config.py.

I’m still working on a more convenient way to set this up. Thank you for your patience.

**Comment by xxtkidxx** [comment]
Hi @dan246 
Thank you for your sharing.
I got it running by adding "model1" to the recognition column in the database.
Can you share more about "Manage Rectangle Areas" ?  What is the function?

**Comment by dan246** [comment]
@xxtkidxx  The /rectangles/<ID> API is used for creating regions of interest. A later version that can draw polygons is currently under testing. Its function is to draw the region of interest so that recognition is limited to that specific area, and areas outside of it will not be recognized. 
P.S. English is not my native language, so please forgive me for using translation.

**Comment by xxtkidxx** [comment]
Thank you, I understand.
Last question: 
Can I increase the number of Wokers? Does it increase system speed?
How many cameras have you processed using this architecture? (03 Worker)

**Comment by dan246** [comment]
@xxtkidxx 

You can increase the number of workers in redis.yaml. Just make sure to set the WORKER_ID, and update self.num_workers = 3 in camera_ctrler/camera_manager.py to match your number of workers. This will distribute the cameras evenly for CPU processing. If you use GPU decoding (FFMPEG) for rtsp_url, it will improve efficiency.

I have successfully used this worker-based architecture to process more than 20 cameras (with 10 workers), achieving balanced load distribution and efficient resource utilization. The exact number may vary depending on the complexity of the camera streams and system resources. For HTTP-based cameras, the system can handle over 100 cameras due to the lack of decoding requirements. However, for RTSP cameras, decoding and latency need to be considered. We recommend using FFMPEG's GPU decoding for effective camera processing.

**Comment by dan246** [comment]
The processing of 20 cameras is purely CPU-based, while GPU processing can theoretically double this capacity.

**Comment by dan246** [comment]
> @xxtkidxx
> 
> You can increase the number of workers in redis.yaml. Just make sure to set the WORKER_ID, and update self.num_workers = 3 in camera_ctrler/camera_manager.py to match your number of workers. This will distribute the cameras evenly for CPU processing. If you use GPU decoding (FFMPEG) for rtsp_url, it will improve efficiency.
> 
> I have successfully used this worker-based architecture to process more than 20 cameras (with 10 workers), achieving balanced load distribution and efficient resource utilization. The exact number may vary depending on the complexity of the camera streams and system resources. For HTTP-based cameras, the system can handle over 100 cameras due to the lack of decoding requirements. However, for RTSP cameras, decoding and latency need to be considered. We recommend using FFMPEG's GPU decoding for effective camera processing.


The processing of 20 cameras is purely CPU-based, while GPU processing can theoretically double this capacity.
